disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - MasterProject
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

# implicitly
line_length: 100

type_name:
excluded: # excluded via string array
    - E
    - T

identifier_name:
  excluded: # excluded via string array
    - id

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 10

cyclomatic_complexity:
  ignores_case_statements: true